# Development build
version: "3.8"
services:
  backend-api:
    build:
      context: ./backend
      target: development
    restart: unless-stopped
    container_name: backend-api
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    networks:
      - app-network
      - back-network
    depends_on:
      - db
      - s3

  frontend-app:
    build:
      context: ./frontend
      target: development
    command: sh -c "npm i && npm run dev"
    restart: unless-stopped
    container_name: frontend-app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    container_name: db-postgres
    image: postgres:15.3
    # environment:
    # POSTGRES_USER: ${POSTGRES_USER}
    # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # POSTGRES_DB: db_saline_royale
    # DATABASE_HOST: postgres
    env_file:
      - ./backend/development.env
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - back-network

  s3:
    image: zenko/cloudserver
    container_name: s3
    ports:
      - "8000:8000"
    volumes:
      - ./s3-config/config.json:/usr/src/app/config.docker
      - ./s3-config/credentials:/root/.aws/credentials
      - s3-data:/usr/src/app/localData
      - s3-metadata:/usr/src/app/localMetadata
    environment:
      S3DATA: multiple
      REMOTE_MANAGEMENT_DISABLE: 1
      LISTEN_ADDR: 0.0.0.0
      # These variables specify authentication credentials for an account named "CustomAccount"
      # SCALITY_ACCESS_KEY_ID: ${SCALITY_ACCESS_KEY_ID}
      # SCALITY_SECRET_ACCESS_KEY: ${SCALITY_SECRET_ACCESS_KEY}
    env_file:
      - ./backend/development.env
    restart: unless-stopped
    command: /bin/sh -c "cp -R ./config.docker config.json && yarn start"
    networks:
      - app-network

  # grafana:
  #     container_name: grafana
  #     image: grafana/grafana:latest
  #     restart: unless-stopped
  #     ports:
  #       - 3001:3000
  #     volumes:
  #       - ./grafana:/var/lib/grafana
  #     networks:
  #       - back-network
  #     depends_on:
  #       - db

volumes:
  s3-data:
  s3-metadata:

networks:
  app-network:
  back-network:

# docker-compose -f docker-compose.yml up -d --build
