# Development build
version: "3.8"
services:
  backend-api:
    container_name: backend-api-${ENVIRONMENT:-development}
    build:
      context: ./backend
    environment:
      CONFIG_NAME: ${ENVIRONMENT:-development}

    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    networks:
      - app-network
      - back-network
    depends_on:
      - db
      - s3

  frontend-app:
    container_name: frontend-app-${ENVIRONMENT:-development}
    build:
      context: ./frontend
      target: ${ENVIRONMENT:-development}

    command: sh -c "npm i && npm run dev"
    restart: unless-stopped

    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    container_name: db-postgres-${ENVIRONMENT:-development}
    image: postgres:15.3
    env_file:
      - ./backend/${ENVIRONMENT:-development}.env

    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - back-network

  s3:
    image: zenko/cloudserver:latest-7.10.19
    container_name: s3-${ENVIRONMENT:-development}
    ports:
      - "8000:8000"
    volumes:
      - ./s3-config/config.json:/usr/src/app/config.docker
      - ./s3-config/credentials:/root/.aws/credentials
      - s3-data:/usr/src/app/localData
      - s3-metadata:/usr/src/app/localMetadata
    environment:
      S3DATA: multiple
      REMOTE_MANAGEMENT_DISABLE: 1
      LISTEN_ADDR: 0.0.0.0
      # These variables specify authentication credentials for an account named "CustomAccount"
      # SCALITY_ACCESS_KEY_ID: ${SCALITY_ACCESS_KEY_ID}
      # SCALITY_SECRET_ACCESS_KEY: ${SCALITY_SECRET_ACCESS_KEY}
    env_file:
      - ./backend/${ENVIRONMENT:-development}.env

    restart: unless-stopped
    command: /bin/sh -c "cp -R ./config.docker config.json && yarn start"
    networks:
      - app-network

volumes:
  s3-data:
  s3-metadata:

networks:
  app-network:
  back-network:
# docker compose -f docker-compose.yml up -d --build
