"""add s3_object table and modify video, partition, image, subtitle

Revision ID: 03a026d10d06
Revises: a2d344361f5d
Create Date: 2023-07-19 13:30:48.289537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03a026d10d06"
down_revision = "a2d344361f5d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "s3_object",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("bucket", sa.String(), nullable=False),
        sa.Column("public", sa.Boolean(), nullable=False),
        sa.Column("major_type", sa.String(), nullable=False),
        sa.Column("minor_type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("image", sa.Column("name", sa.String(), nullable=False))
    op.add_column("image", sa.Column("s3_object_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "image", "s3_object", ["s3_object_id"], ["id"])
    op.drop_column("image", "title")
    op.drop_column("image", "file_name")
    op.add_column("partition", sa.Column("name", sa.String(), nullable=False))
    op.add_column("partition", sa.Column("s3_object_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "partition", "s3_object", ["s3_object_id"], ["id"])
    op.drop_column("partition", "file_name")
    op.add_column("subtitle", sa.Column("name", sa.String(), nullable=False))
    op.add_column("subtitle", sa.Column("s3_object_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "subtitle", "s3_object", ["s3_object_id"], ["id"])
    op.drop_column("subtitle", "file_name")
    op.add_column("video", sa.Column("name", sa.String(), nullable=False))
    op.add_column("video", sa.Column("s3_object_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "video", "s3_object", ["s3_object_id"], ["id"])
    op.drop_column("video", "title")
    op.drop_column("video", "file_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video",
        sa.Column("file_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "video", sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "video", type_="foreignkey")
    op.drop_column("video", "s3_object_id")
    op.drop_column("video", "name")
    op.add_column(
        "subtitle",
        sa.Column("file_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "subtitle", type_="foreignkey")
    op.drop_column("subtitle", "s3_object_id")
    op.drop_column("subtitle", "name")
    op.add_column(
        "partition",
        sa.Column("file_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "partition", type_="foreignkey")
    op.drop_column("partition", "s3_object_id")
    op.drop_column("partition", "name")
    op.add_column(
        "image",
        sa.Column("file_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "image", sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "image", type_="foreignkey")
    op.drop_column("image", "s3_object_id")
    op.drop_column("image", "name")
    op.drop_table("s3_object")
    # ### end Alembic commands ###
