"""update name table, add title to work analysis

Revision ID: d3e6cca7f34d
Revises: ecca29441e2f
Create Date: 2023-07-31 09:02:44.103190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3e6cca7f34d"
down_revision = "ecca29441e2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("academy", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("academy_updated_by_fkey"), "academy", "user", ["updated_by"], ["id"]
    )
    op.add_column("image", sa.Column("filename", sa.String(), nullable=False))
    op.drop_column("image", "name")
    op.add_column("partition", sa.Column("filename", sa.String(), nullable=False))
    op.drop_column("partition", "name")
    op.add_column("subtitle", sa.Column("filename", sa.String(), nullable=False))
    op.drop_column("subtitle", "name")
    op.add_column("video", sa.Column("filename", sa.String(), nullable=False))
    op.drop_column("video", "name")
    op.add_column("work_analysis", sa.Column("title", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_analysis", "title")
    op.add_column(
        "video", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("video", "filename")
    op.add_column(
        "subtitle", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("subtitle", "filename")
    op.add_column(
        "partition",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("partition", "filename")
    op.add_column(
        "image", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("image", "filename")
    op.drop_constraint(op.f("academy_updated_by_fkey"), "academy", type_="foreignkey")
    op.drop_column("academy", "updated_by")
    # ### end Alembic commands ###
