"""add meta to masterclass

Revision ID: 2e79345fc185
Revises: 65c17f8a6aca
Create Date: 2023-08-31 08:52:02.425590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e79345fc185"
down_revision = "65c17f8a6aca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "masterclass_meta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("masterclass_id", sa.UUID(), nullable=False),
        sa.Column("meta_key", sa.String(), nullable=False),
        sa.Column("meta_value", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["masterclass_id"],
            ["masterclass.id"],
            name=op.f("masterclass_meta_masterclass_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("masterclass_meta_pkey")),
        sa.UniqueConstraint("id", name=op.f("masterclass_meta_id_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("masterclass_meta")
    # ### end Alembic commands ###
