"""update work analysis translation

Revision ID: 199f771aaa97
Revises: e00d13d99399
Create Date: 2023-08-12 08:27:54.716436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "199f771aaa97"
down_revision = "e00d13d99399"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_analysis_translation", sa.Column("title", sa.String(), nullable=False)
    )
    op.drop_constraint(
        "biography_translation_biography_id_fkey",
        "biography_translation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("biography_translation_biography_id_fkey"),
        "biography_translation",
        "biography",
        ["biography_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "work_analysis_translation_work_analysis_id_fkey",
        "work_analysis_translation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("work_analysis_translation_work_analysis_id_fkey"),
        "work_analysis_translation",
        "work_analysis",
        ["work_analysis_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_analysis_translation", "title")
    op.drop_constraint(
        op.f("work_analysis_translation_work_analysis_id_fkey"),
        "work_analysis_translation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "work_analysis_translation_work_analysis_id_fkey",
        "work_analysis_translation",
        "work_analysis",
        ["work_analysis_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("biography_translation_biography_id_fkey"),
        "biography_translation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "biography_translation_biography_id_fkey",
        "biography_translation",
        "biography",
        ["biography_id"],
        ["id"],
    )
    # ### end Alembic commands ###
