"""link subtitle to masterclass

Revision ID: 2f7ca43e3bca
Revises: 7a748bd6499e
Create Date: 2023-08-11 09:45:57.335875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f7ca43e3bca"
down_revision = "7a748bd6499e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subtitle", sa.Column("masterclass_id", sa.UUID(), nullable=False))
    op.drop_constraint("subtitle_video_id_fkey", "subtitle", type_="foreignkey")
    op.create_foreign_key(
        op.f("subtitle_masterclass_id_fkey"),
        "subtitle",
        "masterclass",
        ["masterclass_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("subtitle", "video_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subtitle",
        sa.Column("video_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("subtitle_masterclass_id_fkey"), "subtitle", type_="foreignkey"
    )
    op.create_foreign_key(
        "subtitle_video_id_fkey", "subtitle", "video", ["video_id"], ["id"]
    )
    op.drop_column("subtitle", "masterclass_id")
    # ### end Alembic commands ###
