"""add image_id to academy

Revision ID: 12c692bece34
Revises: 2e79345fc185
Create Date: 2023-09-05 07:50:29.595580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "12c692bece34"
down_revision = "2e79345fc185"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("academy", sa.Column("image_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("academy", "image_id")
    # ### end Alembic commands ###
