"""annotation_system

Revision ID: b859f8bb9997
Revises: a3e24a61b27e
Create Date: 2023-08-09 22:42:07.745903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b859f8bb9997"
down_revision = "a3e24a61b27e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "partition_annotation_annotation_id_fkey",
        "partition_annotation",
        type_="foreignkey",
    )
    op.drop_constraint(
        "partition_annotation_partition_id_fkey",
        "partition_annotation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("partition_annotation_partition_id_fkey"),
        "partition_annotation",
        "partition",
        ["partition_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("partition_annotation_annotation_id_fkey"),
        "partition_annotation",
        "annotation",
        ["annotation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("partition_annotation_annotation_id_fkey"),
        "partition_annotation",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("partition_annotation_partition_id_fkey"),
        "partition_annotation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "partition_annotation_partition_id_fkey",
        "partition_annotation",
        "partition",
        ["partition_id"],
        ["id"],
    )
    op.create_foreign_key(
        "partition_annotation_annotation_id_fkey",
        "partition_annotation",
        "annotation",
        ["annotation_id"],
        ["id"],
    )
    # ### end Alembic commands ###
