"""add image academy, simplify image masterclass

Revision ID: 2b4920b0dd1d
Revises: 2e79345fc185
Create Date: 2023-09-05 10:38:44.836644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b4920b0dd1d"
down_revision = "2e79345fc185"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("masterclass_image")
    op.add_column("academy", sa.Column("image_id", sa.UUID(), nullable=True))
    op.add_column("masterclass", sa.Column("image_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("masterclass", "image_id")
    op.drop_column("academy", "image_id")
    op.create_table(
        "masterclass_image",
        sa.Column("masterclass_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("image_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"], ["image.id"], name="masterclass_image_image_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["masterclass_id"],
            ["masterclass.id"],
            name="masterclass_image_masterclass_id_fkey",
        ),
    )
    # ### end Alembic commands ###
