"""annotation_system

Revision ID: e00d13d99399
Revises: a3e24a61b27e
Create Date: 2023-08-10 09:16:15.557602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e00d13d99399"
down_revision = "a3e24a61b27e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("partition_annotation")
    op.add_column("annotation", sa.Column("partition_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        op.f("annotation_partition_id_fkey"),
        "annotation",
        "partition",
        ["partition_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("annotation_partition_id_fkey"), "annotation", type_="foreignkey"
    )
    op.drop_column("annotation", "partition_id")
    op.create_table(
        "partition_annotation",
        sa.Column("partition_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("annotation_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotation.id"],
            name="partition_annotation_annotation_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["partition_id"],
            ["partition.id"],
            name="partition_annotation_partition_id_fkey",
        ),
    )
    # ### end Alembic commands ###
