"""Add roles

Revision ID: 697d8dc19104
Revises: 65c17f8a6aca
Create Date: 2023-09-05 11:57:13.345393

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "697d8dc19104"
down_revision = "65c17f8a6aca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "service_rights", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("academy_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["academy_id"], ["academy.id"], name=op.f("role_academy_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("role_pkey")),
    )
    op.add_column("user", sa.Column("role_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("user_role_id_fkey"), "user", "role", ["role_id"], ["id"]
    )
    op.drop_column("user", "primary_role")
    op.drop_column("user", "secondary_role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "secondary_role",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column("primary_role", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("user_role_id_fkey"), "user", type_="foreignkey")
    op.drop_column("user", "role_id")
    op.drop_table("role")
    op.drop_table("log", schema="logging")
    # ### end Alembic commands ###
