"""Updates tables

Revision ID: 3d3845c9e048
Revises: ab2dd7ca6ca7
Create Date: 2023-07-07 18:52:43.739234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3845c9e048'
down_revision = 'ab2dd7ca6ca7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'academy', ['id'])
    op.create_unique_constraint(None, 'reset_token', ['id'])
    op.add_column('user', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_foreign_key(None, 'user', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'created_by')
    op.drop_constraint(None, 'reset_token', type_='unique')
    op.drop_constraint(None, 'academy', type_='unique')
    # ### end Alembic commands ###
