"""Update partition, subtitle, video, image

Revision ID: 6064a459b56d
Revises: db1238245158
Create Date: 2023-07-17 17:34:03.235132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6064a459b56d'
down_revision = 'db1238245158'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('name', sa.String(), nullable=False))
    op.add_column('partition', sa.Column('name', sa.String(), nullable=False))
    op.add_column('subtitle', sa.Column('name', sa.String(), nullable=False))
    op.add_column('video', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('video', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('video', 'name')
    op.drop_column('subtitle', 'name')
    op.drop_column('partition', 'name')
    op.drop_column('image', 'name')
    # ### end Alembic commands ###
