"""delete fk reset_token

Revision ID: a2d344361f5d
Revises: 6eee6ba2e907
Create Date: 2023-07-11 14:20:57.729097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d344361f5d'
down_revision = '6eee6ba2e907'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reset_token_user_id_fkey', 'reset_token', type_='foreignkey')
    op.create_foreign_key(None, 'reset_token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reset_token', type_='foreignkey')
    op.create_foreign_key('reset_token_user_id_fkey', 'reset_token', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
