"""added cascade on delete user or masterclass for masterclass_user_table

Revision ID: bb3e3a746c26
Revises: a2d344361f5d
Create Date: 2023-07-14 09:53:33.683970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3e3a746c26'
down_revision = 'a2d344361f5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('masterclass_user_masterclass_id_fkey', 'masterclass_user', type_='foreignkey')
    op.drop_constraint('masterclass_user_user_id_fkey', 'masterclass_user', type_='foreignkey')
    op.create_foreign_key(None, 'masterclass_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'masterclass_user', 'masterclass', ['masterclass_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'masterclass_user', type_='foreignkey')
    op.drop_constraint(None, 'masterclass_user', type_='foreignkey')
    op.create_foreign_key('masterclass_user_user_id_fkey', 'masterclass_user', 'user', ['user_id'], ['id'])
    op.create_foreign_key('masterclass_user_masterclass_id_fkey', 'masterclass_user', 'masterclass', ['masterclass_id'], ['id'])
    # ### end Alembic commands ###
