"""add secondary role to user, rename masterclass_user role to masterclass_role

Revision ID: ef905a5ecf6f
Revises: 2335c7d393fc
Create Date: 2023-07-11 10:55:26.052815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef905a5ecf6f"
down_revision = "2335c7d393fc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_tag",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    op.create_unique_constraint(None, "masterclass", ["id"])
    op.create_unique_constraint(None, "masterclass_user", ["id"])

    op.alter_column(
        "masterclass_user",
        "role",
        new_column_name="masterclass_role",
        type_=sa.String(),
        nullable=False,
    )
    op.alter_column(
        "user",
        "role",
        new_column_name="primary_role",
        type_=sa.String(),
        nullable=False,
    )
    op.add_column(
        "user", sa.Column("secondary_role", sa.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "secondary_role")
    op.alter_column(
        "masterclass_user",
        "masterclass_role",
        new_column_name="role",
        type_=sa.String(),
        nullable=False,
    )
    op.alter_column(
        "user",
        "primary_role",
        new_column_name="role",
        type_=sa.String(),
        nullable=False,
    )

    op.drop_constraint("masterclass_user_id_key", "masterclass_user", type_="unique")
    op.drop_column("masterclass_user", "masterclass_role")
    op.drop_constraint("masterclass_id_key", "masterclass", type_="unique")
    op.drop_table("user_tag")
    # ### end Alembic commands ###
