export const Types = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_PROFILE_PICTURE: 'UPDATE_PROFILE_PICTURE',
    DISCONNECT: 'DISCONNECT',
    SORT_BY: 'SORT_BY'
}