name: "Test backend"

on:
  pull_request:
    branches:
      - "**"

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: python:3.11.4-slim

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd backend
          apt-get update
          apt-get -y install libpq-dev gcc
          pip install poetry==1.4.2
          poetry export --without-hashes --dev -f requirements.txt -o requirements.txt
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend
          pytest ./src/tests
