name: "Test backend"

on:
  pull_request:
    branches:
      - "**"

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: python:3.11.4-alpine3.18

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd backend
          pip install poetry==1.4.2
          poetry export -f requirements.txt --output requirements.txt --without-hashes
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest ./src/tests
